name: overload
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Gulf
      fonts:
        - asset: assets/fonts/GulfsDisplay-Normal.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoFlex-VariableFont.ttf

    - family: Dancing
      fonts:
        - asset: assets/fonts/Dancing-Script.ttf

    - family: JostItalic
      fonts:
        - asset: assets/fonts/Jost-Italic.ttf

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost.ttf

    - family: KarlaItalic
      fonts:
        - asset: assets/fonts/Karla-Italic.ttf

    - family: Karla
      fonts:
        - asset: assets/fonts/Karla.ttf

    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/SignikaNegative.ttf

    - family: UbuntuSansMonoItalic
      fonts:
        - asset: assets/fonts/UbuntuSansMono-Italic.ttf

    - family: UbuntuSansMono
      fonts:
        - asset: assets/fonts/UbuntuSansMono.ttf

  assets:
    - assets/img/
    - assets/img/homepage icons/
    - assets/img/homepage-icons-v2/
